spring.application.name=McpSpring-Server

spring.ai.mcp.server.name=spring-mcp-server
spring.ai.mcp.server.type=sync
spring.ai.mcp.server.sse-endpoint=/sse
spring.ai.mcp.server.sse-message-endpoint=/mcp/message
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.request-timeout=120s
spring.ai.mcp.server.connection-timeout=30s
spring.ai.azure.openai.chat.options.max-output-tokens=800
spring.ai.azure.openai.chat.options.temperature=0.0
server.port=8899
logging.level.io.modelcontextprotocol=TRACE
logging.level.org.springframework.ai.mcp=TRACE


spring.ai.azure.openai.api-key=${AZURE_OPENAI_API_KEY}
spring.ai.azure.openai.endpoint=${AZURE_OPENAI_ENDPOINT}
spring.ai.azure.openai.chat.options.deployment-name=gpt-4o



spring.datasource.url=${datasource_url}
spring.datasource.username=${datasource_username}
spring.datasource.password=${datasource_password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
